# Generated by Django 5.1 on 2024-08-10 01:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuario', '0002_intereses_profile_intereses'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='age',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
